from typing import Protocol
import threading
class ThreadOrProcess(Protocol):
    name:str
    daemon:bool
    #ident:int
    #pid:int
    def start(self) -> None: ...
    def join(self, timeout: float | None = None) -> None: ...
    def is_alive(self) -> bool: ...
    #def isDaemon(self) -> bool: ...
    #def setDaemon(self,daemonic:bool) -> None: ...
    #def getName(self) -> str: ...
    #def setName(self,name:str) -> None: ...

threading.Thread